service: cpt

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-3
  stage: dev
  environment:
    TELEGRAM_BOT_KEY: ${env:TELEGRAM_BOT_KEY}

package:
  individually: true
  exclude:
    - "*"

functions:
  cptf:
    handler: dist/handler.handle
    memorySize: 128
    package:
      include:
        - dist
        - node_modules
    events:
      - http:
          path: cod-performance-tracker
          method: post
          cors: true
